#!/usr/bin/env bash
# This script transfers a file from client to server using scp

# Check if the number of parameters is less than 3
if [ $# -lt 3 ]; then
echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
scp -i $4 -o StrictHostKeyChecking=no $1 $3@$2:~/
fi
