#!/usr/bin/env bash
# Transfers a file from the client to a server using scp

# Display usage if less than 4 parameters are passed
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Extract parameters
file_path=$1
server_ip=$2
username=$3
ssh_key=$4

# Transfer the file to the user home directory on the server
scp -i "$ssh_key" -o StrictHostKeyChecking=no "$file_path" "$username@$server_ip":~/
