#!/usr/bin/env bash

# Commands to install Nginx on Web-Sever-01

# Updating Packages before making Installations
sudo apt-get update
sudo apt-get -y install nginx

# Configuring the Uncomplicated Firewall (UFW) to allow incoming traffic for the Nginx HTTP service
sudo ufw allow 'Nginx HTTP'

# Creating an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Restarting Nginx
sudo service nginx start

# Adding a delay to allow Nginx to fully start
sleep 2

# Testing Nginx configurations for Syntax errors
sudo nginx -t
