#!/usr/bin/env bash
# Install and configure Nginx web server

# Update package list
sudo apt-get update

# Install Nginx
sudo apt-get install nginx -y

# Configure Nginx
echo "server {
    listen 80;
    server_name _;

    location / {
        echo 'Hello World!';
    }
}" | sudo tee /etc/nginx/sites-available/default > /dev/null

# Restart Nginx
sudo service nginx restart
