#!/usr/bin/env bash
# This script configures the nginx server to have a custom 404 page

# Update package list and install nginx
apt-get update
apt-get install -y nginx

# Create a default HTML page
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Add a rewrite rule for redirection
sed -i "46i rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default

# Create a custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null

# Configure nginx to use the custom 404 page
sed -i "46i error_page 404 /custom_404.html;" /etc/nginx/sites-available/default

# Restart nginx to apply changes
service nginx restart

