#!/usr/bin/env bash
# Configures Nginx to add a custom HTTP header

sudo apt-get update
sudo apt-get -y install nginx

# Add custom header to Nginx configuration
sudo sed -i '19 i \\tadd_header X-Served-By $HOSTNAME;' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo service nginx restart
