#!/usr/bin/env bash
# Configures Nginx to add a custom HTTP header

sudo apt-get update
sudo apt-get -y install nginx

# Add custom header to Nginx configuration
echo "add_header X-Served-By \$hostname;" | sudo tee -a /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo service nginx restart
