#!/usr/bin/env bash
# Installs and configures HAProxy on lb-01 server

sudo apt-get update
sudo apt-get -y install haproxy

# Configure HAProxy
sudo sed -i 's/.*frontend.*/frontend http_front\n    bind *:80\n    mode http\n    default_backend http_back/' /etc/haproxy/haproxy.cfg
sudo sh -c 'echo "backend http_back\n    balance roundrobin\n    server web-01 [STUDENT_ID]-web-01:80 check\n    server web-02 [STUDENT_ID]-web-02:80 check" >> /etc/haproxy/haproxy.cfg'

# Restart HAProxy to apply changes
sudo service haproxy restart
