#!/usr/bin/env bash
# configures an Nginx server to listen on port 80

#remove the default Nginx configuration file
rm /etc/nginx/sites-enabled/default
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
