#!/usr/bin/env bash
# Script for Task 9

# Function to handle SIGTERM
handle_sigterm() {
    echo "I hate the kill command"
    cleanup_and_exit
}

# Function to handle SIGINT
handle_sigint() {
    echo "Y U no love me?!"
    cleanup_and_exit
}

# Function to handle SIGQUIT
handle_sigquit() {
    cleanup_and_exit
}

cleanup_and_exit() {
    rm -f /var/run/myscript.pid
    exit 0
}

# Writing the PID to /var/run/myscript.pid
echo $$ > /var/run/myscript.pid

# Assigning signal handlers
trap 'handle_sigterm' SIGTERM
trap 'handle_sigint' SIGINT
trap 'handle_sigquit' SIGQUIT

# Infinite loop displaying "To infinity and beyond"
while true; do
    echo "To infinity and beyond"
    sleep 2
done
