#!/usr/bin/env bash
# This script reacts to various signals and manages the PID file.

trap 'echo "I hate the kill command"; continue' SIGTERM
trap 'echo "Y U no love me?!"; continue' SIGINT
trap 'rm /var/run/myscript.pid; exit' SIGQUIT

echo "$$" > /var/run/myscript.pid

while true; do
  echo "To infinity and beyond" > /tmp/my_process
  sleep 2
done
