#!/usr/bin/env bash

# Trap SIGTERM signal and print "I am invincible!!!" instead of terminating.
trap "echo 'I am invincible!!!'" SIGTERM

# Infinite loop
while true; do
    echo "To infinity and beyond"
    sleep 2
done

