#!/usr/bin/env bash
# This script handles various signals.

trap 'echo "I am invincible!!!"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm /var/run/myscript.pid; exit' SIGQUIT

echo "$$" > /var/run/myscript.pid

while true; do
  echo "To infinity and beyond"
  sleep 2
done

