#!/usr/bin/env bash
# Parsing Apache log, grouping by IP and HTTP status code, then sorting

# Parse the log for IP and HTTP status, then sort the results, group and count them, and finally sort in descending order of occurrences
awk '{print $1, $9}' apache-access.log | sort | uniq -c | sort -nr
