#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code, displays this data but filters out HTTP status 200 and 304

awk '{
    ip_status[$1 " " $9]++
}
END {
    for (key in ip_status) {
        if (key !~ / 200$/ && key !~ / 304$/) {
            print ip_status[key], key
        }
    }
}' apache-access.log | sort -nr

