#!/usr/bin/env bash
# Description: This script loops through numbers1 to 10. Depending on the iteration number, it prints either "bad luck", "good luck", or "Best School".

count=1
while [ $count -le 10  ]; do
if [ $count -eq 3 ]; then
echo "Best School"
echo "bad luck"
elif [ $count -eq 8 ]; then 
echo "good luck"
else
echo "Best School"
fi
count=$((count+1))
done

exit 0;
