#!/usr/bin/env bash
# This script changes the IP resolution of localhost and facebook.com

# Add entries to /etc/hosts
echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
