#!/usr/bin/env bash

sed -i 's/#user www-data/user nginx/g' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default


# give owner permissions to read and write to the config file
chmod 644 /etc/nginx/nginx.conf

# apache may interfere with nginx so kill the process if it is running
pkill apache2

# Start Nginx
sudo -u nginx service nginx start
