#!/usr/bin/env bash

# Ensure Nginx is stopped before making changes
service nginx stop

# Modify Nginx configuration to run as nginx user and listen on port 8080
sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/listen 80;/listen 8080;/g' /etc/nginx/sites-available/default

# Start Nginx
service nginx start
