#!/usr/bin/env bash
# This script connects to the server using the private key ~/.ssh/school with the user ubuntu.

# Connect to the server using SSH with the private key
ssh -i ~/.ssh/school ubuntu@34.207.61.41

