#!/usr/bin/env bash
# This script generates an RSA key pair named 'school' with a passphrase.

# Generate the key pair
ssh-keygen -t rsa -b 4096 -C "vagrant@ubuntu" -f ~/.ssh/school

# Display the key generation message
echo "Generating public/private rsa key pair."

# Display the files created
ls -l ~/.ssh/school*
