#!/usr/bin/env bash
# This script creates an RSA key pair with the name 'school' and a passphrase 'betty'.

# Generate the RSA key pair with a passphrase
ssh-keygen -t rsa -b 4096 -f ~/.ssh/school -C "vagrant@ubuntu"
